#!/usr/bin/env ruby
require "lucid_cop"
require "optparse"

options = {}

OptionParser.new do |opts|
  opts.banner = 'Usage: lucidcop [files]'

  opts.on('--disable [CHECKS]', 'Disable checks. Separate by ","') do |checks|
    options[:disable] = checks.split(',')
  end

  opts.on('--enable [CHECKS]', 'Enable checks. Separate by ","') do |checks|
    options[:enable] = checks.split(',')
  end

  opts.on('-s', '--specpath [spec/s]', 'Feature specs path') do |spec|
    options[:specs] = spec
  end
end.parse!

cop = LucidCop::LucidCop.new

cop.disable(options[:disable]) if options.key? :disable
cop.enable options[:enable] if options.key? :enable

files = ARGV.map { |pattern| Dir.glob(pattern) }.flatten
files += Dir.glob(options[:files]) if options.key? :files

if ARGV.empty? && !options.key?(:specs)
  files = Dir.glob('features/**/*.feature')
end

files.each do |file|
  puts("Analyzing #{file}")
  cop.analyze(file)
end

puts("******************")
puts(cop.inspect)
puts("Files: #{files}")
