#!/usr/bin/env ruby
require "lucid_cop"
require "optparse"

options = {}

OptionParser.new do |opts|
  opts.banner = 'Usage: lucidcop [files]'

  opts.on('--disable [CHECKS]', 'Disable checks. Separate by ","') do |checks|
    options[:disable] = checks.split(',')
  end

  opts.on('--enable [CHECKS]', 'Enable checks. Separate by ","') do |checks|
    options[:enable] = checks.split(',')
  end

  opts.on('-s', '--specpath [spec/s]', 'Feature specs path') do |spec|
    options[:specs] = spec
  end

  opts.on('-v', '--[no-]verbose', 'Run with verbose output') do |verbose|
    options[:verbose] = verbose
  end
end.parse!

cop = LucidCop::LucidCop.new

cop.disable(options[:disable]) if options.key? :disable
cop.enable options[:enable] if options.key? :enable
cop.enable_verbose(options[:verbose]) if options.key? :verbose
cop.setup_cops

files = ARGV.map { |pattern| Dir.glob(pattern) }.flatten
files += Dir.glob(options[:files]) if options.key? :files

files = Dir.glob('features/**/*.feature') if ARGV.empty? && !options.key?(:specs)

files.each do |file|
  cop.analyze(file)
end

exit cop.report
